### PR TITLE
'First Russians' Text & Translation

### PR DESCRIPTION
**Pull request by mkorahais**
Transcribed the text and translation for 'First Russians'.

### CODE REVIEW

**Comment by jcrippen** [comment]
Can you rename the Text file to Original? There’s several typos in the original that need to be corrected and the spelling needs to be regularized to the corpus standard. I can then duplicate the Original to a new Text file and do the conversion so you can see what the major differences are.

Also, change Teiḵweidée → Teiḵweidí in the metadata. This is one of the spelling changes; older practice wrote variable length final vowels as long but they are now written as short.

**Comment by scable413** [comment]
Hi James,

Is this message to me, or to someone else who’s working on that GitHub? I haven’t been on there in a long while now, and so it would take some time to relearn things.

Best,

-- Seth.

**Comment by mkorahais** [comment]
I just added the original and translation for another text, 'Raven Boat', from D&D 1987. I'm seeing that it combined with my existing pull request for the first text. Is this the correct way to do this, or is it possible to start an independent pull request?

Also, I found a typo in the D&D book in English: they spell "droppped" with three p's. Should I correct this typo or leave it how it is?

**Comment by jcrippen** [comment]
It should be possible to split the pull requests in two, but we’ll go ahead with both for now.

**Pull request merged**
